#!/usr/bin/env python

from PIL import Image

im = Image.open("./image.jpg")
out = Image.new('RGB', im.size, 0xffffff)

width, height = im.size
for x in range(width):
    for y in range(height):
        r,g,b = im.getpixel((x,y))
        gs_value = (r + g + b) / 3
        out.putpixel((x,y), (gs_value, gs_value, gs_value))

out.save('grayscale.png')
